name: fast_location
description: App de consulta de CEP - desafio TIC
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_ios: ^2.0.9
  map_launcher: ^4.4.2
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/fastlocation.png
    - assets/images/historicofl.png
    - assets/images/voltarfl.png
    - assets/images/lixofl.png

# Configuração do ícone do app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fastlocation.png"
